// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLYpGpFKdkApEuSgibWRnxWjwSMdUroTw',
    appId: '1:9954417221:web:5422622bd4ce2b0a37e12c',
    messagingSenderId: '9954417221',
    projectId: 'airbnb-a667b',
    authDomain: 'airbnb-a667b.firebaseapp.com',
    storageBucket: 'airbnb-a667b.firebasestorage.app',
    measurementId: 'G-NQE62SMP5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Kxzjpbn0IZPJPcHF_VrQ1kMrenaE8V8',
    appId: '1:9954417221:android:4607da55e6fd2dd337e12c',
    messagingSenderId: '9954417221',
    projectId: 'airbnb-a667b',
    storageBucket: 'airbnb-a667b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAboS02T6UdbU0Gy6SELFZcryR3MPtL7_Y',
    appId: '1:9954417221:ios:c6fbecd97cf34c0937e12c',
    messagingSenderId: '9954417221',
    projectId: 'airbnb-a667b',
    storageBucket: 'airbnb-a667b.firebasestorage.app',
    iosBundleId: 'com.peanut.airbnb',
  );
}
